apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-bootstrap-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-control-plane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
---
apiVersion: v1
kind: Namespace
metadata:
  name: capg-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 

