
## Fehlende Template-CRDs in CAPI Operator <= 0.21 und CAPI <=1.10
## nur per clusterctl verfügbar

# =====================================================================
# 1) Infrastruktur-Vorlage (Projekt / Region / Netzwerk)
# =====================================================================
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedClusterTemplate
metadata:
  name: gke-standard-cluster
  namespace: default
spec:
  template:
    spec:
      project: cluster-01-290863
      region:  europe-west4
      network:
        name: default

---
# =====================================================================
# 2) Control-Plane-Vorlage (GKE-Version, Channel, Name)
# =====================================================================
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlaneTemplate
metadata:
  name: gke-standard-control-plane
  namespace: default
spec:
  template:
    spec:
      project:       cluster-01-290863
      location:      ${ location }            # kommt aus Cluster-Variable
      version:       ${ version }             # kommt aus Cluster-Variable
      releaseChannel: stable
      clusterName:   ${ name }                # sichtbarer GKE-Name
      enableAutopilot: false

---
# =====================================================================
# 3) Node-Pool-Vorlage (Maschinentyp, Autoscaling)
# =====================================================================
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedMachinePoolTemplate
metadata:
  name: gke-standard-mp
  namespace: default
spec:
  template:
    spec:
      machineType: e2-standard-4
      diskType:    pd-ssd
      diskSizeGB:  150
      scaling:
        enableAutoscaling: true
        minCount: 3
        maxCount: 6

---
# =====================================================================
# 4) Dummy-Bootstrap-Secret  (Pflichtfeld für MachinePool-Webhook)
# =====================================================================
apiVersion: v1
kind: Secret
metadata:
  name: dummy-bootstrap
  namespace: default
type: Opaque
data: {}

---
# =====================================================================
# 5) ClusterClass – verknüpft die drei Vorlagen
# =====================================================================
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: gke-standard
  namespace: default
spec:
  # --- Infrastruktur & Control-Plane ---------------------------------
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: GCPManagedClusterTemplate
      name: gke-standard-cluster

  controlPlane:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: GCPManagedControlPlaneTemplate
      name: gke-standard-control-plane

  # --- Worker-Pools ---------------------------------------------------
  workers:
    machinePoolClasses:
      - class: default-mp-class      # frei wählbarer Klassenname
        template:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: GCPManagedMachinePoolTemplate
            name: gke-standard-mp
        bootstrap:
          dataSecretName: dummy-bootstrap

  # --- Variablen, die der Cluster später setzt -----------------------
  variables:
    - name: location
      required: true
      schema:
        openAPIV3Schema:
          type: string
    - name: version
      required: true
      schema:
        openAPIV3Schema:
          type: string
    - name: name
      required: true
      schema:
        openAPIV3Schema:
          type: string


# =====================================================================
# 6) Cluster – verweist nur noch auf die Klasse und füllt Variablen
# =====================================================================
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: gke-demo
  namespace: default
spec:
  topology:
    class: gke-standard
    version: "1.32.4"             # → Variable ${ version }
    variables:
      - name: location            # → ${ location }
        value: europe-west4
      - name: name                # → ${ name }  (GKE-Anzeige)
        value: gke-demo
    workers:
      machinePools:
        - class: default-mp-class   # nutzt Worker-Vorlage
          name: mp-0              # frei wählbar
          replicas: 3             # Vielfaches von 3 (regionaler Cluster)

  clusterNetwork:
    pods:
      cidrBlocks: [ "192.168.0.0/16" ]

